%------------------------------------------------------------------------------
% File     : NUM971_5 : TPTP v8.2.0. Released v6.0.0.
% Domain   : Number Theory
% Problem  : Sum of two squares line 104
% Version  : Especial.
% English  : 

% Refs     : [BN10]  Boehme & Nipkow (2010), Sledgehammer: Judgement Day
%          : [Bla13] Blanchette (2011), Email to Geoff Sutcliffe
% Source   : [Bla13]
% Names    : s2s_104 [Bla13]

% Status   : Theorem
% Rating   : 0.00 v7.5.0, 0.33 v7.4.0, 0.25 v7.1.0, 0.67 v6.4.0
% Syntax   : Number of formulae    :  157 (  53 unt;  32 typ;   0 def)
%            Number of atoms       :  242 (  65 equ)
%            Maximal formula atoms :    7 (   1 avg)
%            Number of connectives :  132 (  15   ~;   2   |;  19   &)
%                                         (  53 <=>;  43  =>;   0  <=;   0 <~>)
%            Maximal formula depth :    8 (   3 avg)
%            Maximal term depth    :    6 (   1 avg)
%            Number of types       :    4 (   3 usr)
%            Number of type conns  :   12 (   8   >;   4   *;   0   +;   0  <<)
%            Number of predicates  :   19 (  17 usr;   1 prp; 0-3 aty)
%            Number of functors    :   12 (  12 usr;   5 con; 0-3 aty)
%            Number of variables   :  169 ( 148   !;   0   ?; 169   :)
%                                         (  21  !>;   0  ?*;   0  @-;   0  @+)
% SPC      : TF1_THM_EQU_NAR

% Comments : This file was generated by Isabelle (most likely Sledgehammer)
%            2011-12-13 16:24:26
%------------------------------------------------------------------------------
%----Should-be-implicit typings (3)
tff(ty_tc_HOL_Obool,type,
    bool: $tType ).

tff(ty_tc_Int_Oint,type,
    int: $tType ).

tff(ty_tc_Nat_Onat,type,
    nat: $tType ).

%----Explicit typings (29)
tff(sy_cl_Int_Onumber,type,
    number: 
      !>[A: $tType] : $o ).

tff(sy_cl_Power_Opower,type,
    power: 
      !>[A: $tType] : $o ).

tff(sy_cl_Int_Onumber__ring,type,
    number_ring: 
      !>[A: $tType] : $o ).

tff(sy_cl_Int_Oring__char__0,type,
    ring_char_0: 
      !>[A: $tType] : $o ).

tff(sy_cl_Rings_Omult__zero,type,
    mult_zero: 
      !>[A: $tType] : $o ).

tff(sy_cl_Rings_Osemiring__0,type,
    semiring_0: 
      !>[A: $tType] : $o ).

tff(sy_cl_Rings_Osemiring__1,type,
    semiring_1: 
      !>[A: $tType] : $o ).

tff(sy_cl_Orderings_Olinorder,type,
    linorder: 
      !>[A: $tType] : $o ).

tff(sy_cl_Rings_Ozero__neq__one,type,
    zero_neq_one: 
      !>[A: $tType] : $o ).

tff(sy_cl_Int_Onumber__semiring,type,
    number_semiring: 
      !>[A: $tType] : $o ).

tff(sy_cl_Rings_Olinordered__idom,type,
    linordered_idom: 
      !>[A: $tType] : $o ).

tff(sy_cl_Rings_Ono__zero__divisors,type,
    no_zero_divisors: 
      !>[A: $tType] : $o ).

tff(sy_cl_Rings_Oring__1__no__zero__divisors,type,
    ring_11004092258visors: 
      !>[A: $tType] : $o ).

tff(sy_cl_Groups_Olinordered__ab__group__add,type,
    linord219039673up_add: 
      !>[A: $tType] : $o ).

tff(sy_c_Groups_Oone__class_Oone,type,
    one_one: 
      !>[A: $tType] : A ).

tff(sy_c_Groups_Oplus__class_Oplus,type,
    plus_plus: 
      !>[A: $tType] : ( ( A * A ) > A ) ).

tff(sy_c_Groups_Ozero__class_Ozero,type,
    zero_zero: 
      !>[A: $tType] : A ).

tff(sy_c_Int_OBit0,type,
    bit0: int > int ).

tff(sy_c_Int_OBit1,type,
    bit1: int > int ).

tff(sy_c_Int_OPls,type,
    pls: int ).

tff(sy_c_Int_Onumber__class_Onumber__of,type,
    number_number_of: 
      !>[A: $tType] : ( int > A ) ).

tff(sy_c_Orderings_Oord__class_Oless,type,
    ord_less: 
      !>[A: $tType] : ( ( A * A ) > $o ) ).

tff(sy_c_Orderings_Oord__class_Oless__eq,type,
    ord_less_eq: 
      !>[A: $tType] : ( ( A * A ) > $o ) ).

tff(sy_c_Power_Opower__class_Opower,type,
    power_power: 
      !>[A: $tType] : ( ( A * nat ) > A ) ).

tff(sy_c_fFalse,type,
    fFalse: bool ).

tff(sy_c_fTrue,type,
    fTrue: bool ).

tff(sy_c_pp,type,
    pp: bool > $o ).

tff(sy_v_s____,type,
    s: int ).

tff(sy_v_t____,type,
    t: int ).

%----Relevant facts (98)
tff(fact_0__096_126_A1_A_060_061_At_096,axiom,
    ~ ord_less_eq(int,one_one(int),t) ).

tff(fact_1__0960_A_060_061_As_A_094_A2_096,axiom,
    ord_less_eq(int,zero_zero(int),power_power(int,s,number_number_of(nat,bit0(bit1(pls))))) ).

tff(fact_2__096t_A_060_A1_096,axiom,
    ord_less(int,t,one_one(int)) ).

tff(fact_3__096t_A_061_A0_A_061_061_062_As_A_094_A2_A_L_A1_A_061_A0_096,axiom,
    ( ( t = zero_zero(int) )
   => ( plus_plus(int,power_power(int,s,number_number_of(nat,bit0(bit1(pls)))),one_one(int)) = zero_zero(int) ) ) ).

tff(fact_4__096t_A_060_A0_A_061_061_062_As_A_094_A2_A_L_A1_A_060_A0_096,axiom,
    ( ord_less(int,t,zero_zero(int))
   => ord_less(int,plus_plus(int,power_power(int,s,number_number_of(nat,bit0(bit1(pls)))),one_one(int)),zero_zero(int)) ) ).

tff(fact_5_one__power2,axiom,
    ! [A: $tType] :
      ( semiring_1(A)
     => ( power_power(A,one_one(A),number_number_of(nat,bit0(bit1(pls)))) = one_one(A) ) ) ).

tff(fact_6_zero__power2,axiom,
    ! [A: $tType] :
      ( semiring_1(A)
     => ( power_power(A,zero_zero(A),number_number_of(nat,bit0(bit1(pls)))) = zero_zero(A) ) ) ).

tff(fact_7_zero__eq__power2,axiom,
    ! [A: $tType] :
      ( ring_11004092258visors(A)
     => ! [A2: A] :
          ( ( power_power(A,A2,number_number_of(nat,bit0(bit1(pls)))) = zero_zero(A) )
        <=> ( A2 = zero_zero(A) ) ) ) ).

tff(fact_8_le__special_I2_J,axiom,
    ! [A: $tType] :
      ( ( number_ring(A)
        & linordered_idom(A) )
     => ! [Y: int] :
          ( ord_less_eq(A,one_one(A),number_number_of(A,Y))
        <=> ord_less_eq(int,bit1(pls),Y) ) ) ).

tff(fact_9_le__special_I4_J,axiom,
    ! [A: $tType] :
      ( ( number_ring(A)
        & linordered_idom(A) )
     => ! [X1: int] :
          ( ord_less_eq(A,number_number_of(A,X1),one_one(A))
        <=> ord_less_eq(int,X1,bit1(pls)) ) ) ).

tff(fact_10_le__special_I1_J,axiom,
    ! [A: $tType] :
      ( ( number_ring(A)
        & linordered_idom(A) )
     => ! [Y: int] :
          ( ord_less_eq(A,zero_zero(A),number_number_of(A,Y))
        <=> ord_less_eq(int,pls,Y) ) ) ).

tff(fact_11_le__special_I3_J,axiom,
    ! [A: $tType] :
      ( ( number_ring(A)
        & linordered_idom(A) )
     => ! [X1: int] :
          ( ord_less_eq(A,number_number_of(A,X1),zero_zero(A))
        <=> ord_less_eq(int,X1,pls) ) ) ).

tff(fact_12_power__0__left__number__of,axiom,
    ! [A: $tType] :
      ( ( power(A)
        & semiring_0(A) )
     => ! [W1: int] :
          ( ( ( number_number_of(nat,W1) = zero_zero(nat) )
           => ( power_power(A,zero_zero(A),number_number_of(nat,W1)) = one_one(A) ) )
          & ( ( number_number_of(nat,W1) != zero_zero(nat) )
           => ( power_power(A,zero_zero(A),number_number_of(nat,W1)) = zero_zero(A) ) ) ) ) ).

tff(fact_13_numeral__1__eq__1,axiom,
    ! [A: $tType] :
      ( number_ring(A)
     => ( number_number_of(A,bit1(pls)) = one_one(A) ) ) ).

tff(fact_14_rel__simps_I21_J,axiom,
    ! [K3: int] :
      ( ord_less_eq(int,pls,bit0(K3))
    <=> ord_less_eq(int,pls,K3) ) ).

tff(fact_15_rel__simps_I27_J,axiom,
    ! [K3: int] :
      ( ord_less_eq(int,bit0(K3),pls)
    <=> ord_less_eq(int,K3,pls) ) ).

tff(fact_16_eq__number__of,axiom,
    ! [A: $tType] :
      ( ( number_ring(A)
        & ring_char_0(A) )
     => ! [Y: int,X1: int] :
          ( ( number_number_of(A,X1) = number_number_of(A,Y) )
        <=> ( X1 = Y ) ) ) ).

tff(fact_17_rel__simps_I51_J,axiom,
    ! [L: int,K3: int] :
      ( ( bit1(K3) = bit1(L) )
    <=> ( K3 = L ) ) ).

tff(fact_18_rel__simps_I48_J,axiom,
    ! [L: int,K3: int] :
      ( ( bit0(K3) = bit0(L) )
    <=> ( K3 = L ) ) ).

tff(fact_19_double__eq__0__iff,axiom,
    ! [A: $tType] :
      ( linord219039673up_add(A)
     => ! [A2: A] :
          ( ( plus_plus(A,A2,A2) = zero_zero(A) )
        <=> ( A2 = zero_zero(A) ) ) ) ).

tff(fact_20_rel__simps_I46_J,axiom,
    ! [K: int] : bit1(K) != pls ).

tff(fact_21_rel__simps_I39_J,axiom,
    ! [L1: int] : pls != bit1(L1) ).

tff(fact_22_rel__simps_I50_J,axiom,
    ! [L1: int,K: int] : bit1(K) != bit0(L1) ).

tff(fact_23_rel__simps_I49_J,axiom,
    ! [L1: int,K: int] : bit0(K) != bit1(L1) ).

tff(fact_24_rel__simps_I44_J,axiom,
    ! [K3: int] :
      ( ( bit0(K3) = pls )
    <=> ( K3 = pls ) ) ).

tff(fact_25_rel__simps_I38_J,axiom,
    ! [L: int] :
      ( ( pls = bit0(L) )
    <=> ( pls = L ) ) ).

tff(fact_26_Bit0__Pls,axiom,
    bit0(pls) = pls ).

tff(fact_27_rel__simps_I17_J,axiom,
    ! [L: int,K3: int] :
      ( ord_less(int,bit1(K3),bit1(L))
    <=> ord_less(int,K3,L) ) ).

tff(fact_28_rel__simps_I2_J,axiom,
    ~ ord_less(int,pls,pls) ).

tff(fact_29_rel__simps_I14_J,axiom,
    ! [L: int,K3: int] :
      ( ord_less(int,bit0(K3),bit0(L))
    <=> ord_less(int,K3,L) ) ).

tff(fact_30_rel__simps_I34_J,axiom,
    ! [L: int,K3: int] :
      ( ord_less_eq(int,bit1(K3),bit1(L))
    <=> ord_less_eq(int,K3,L) ) ).

tff(fact_31_rel__simps_I19_J,axiom,
    ord_less_eq(int,pls,pls) ).

tff(fact_32_rel__simps_I31_J,axiom,
    ! [L: int,K3: int] :
      ( ord_less_eq(int,bit0(K3),bit0(L))
    <=> ord_less_eq(int,K3,L) ) ).

tff(fact_33_add__Bit0__Bit0,axiom,
    ! [L1: int,K: int] : plus_plus(int,bit0(K),bit0(L1)) = bit0(plus_plus(int,K,L1)) ).

tff(fact_34_number__of__Pls,axiom,
    ! [A: $tType] :
      ( number_ring(A)
     => ( number_number_of(A,pls) = zero_zero(A) ) ) ).

tff(fact_35_less__number__of,axiom,
    ! [A: $tType] :
      ( ( number_ring(A)
        & linordered_idom(A) )
     => ! [Y: int,X1: int] :
          ( ord_less(A,number_number_of(A,X1),number_number_of(A,Y))
        <=> ord_less(int,X1,Y) ) ) ).

tff(fact_36_le__number__of,axiom,
    ! [A: $tType] :
      ( ( number_ring(A)
        & linordered_idom(A) )
     => ! [Y: int,X1: int] :
          ( ord_less_eq(A,number_number_of(A,X1),number_number_of(A,Y))
        <=> ord_less_eq(int,X1,Y) ) ) ).

tff(fact_37_add__number__of__left,axiom,
    ! [A: $tType] :
      ( number_ring(A)
     => ! [Z: A,W1: int,V: int] : plus_plus(A,number_number_of(A,V),plus_plus(A,number_number_of(A,W1),Z)) = plus_plus(A,number_number_of(A,plus_plus(int,V,W1)),Z) ) ).

tff(fact_38_add__number__of__eq,axiom,
    ! [A: $tType] :
      ( number_ring(A)
     => ! [W1: int,V: int] : plus_plus(A,number_number_of(A,V),number_number_of(A,W1)) = number_number_of(A,plus_plus(int,V,W1)) ) ).

tff(fact_39_rel__simps_I12_J,axiom,
    ! [K3: int] :
      ( ord_less(int,bit1(K3),pls)
    <=> ord_less(int,K3,pls) ) ).

tff(fact_40_nat__number__of__Pls,axiom,
    number_number_of(nat,pls) = zero_zero(nat) ).

tff(fact_41_rel__simps_I16_J,axiom,
    ! [L: int,K3: int] :
      ( ord_less(int,bit1(K3),bit0(L))
    <=> ord_less(int,K3,L) ) ).

tff(fact_42_rel__simps_I10_J,axiom,
    ! [K3: int] :
      ( ord_less(int,bit0(K3),pls)
    <=> ord_less(int,K3,pls) ) ).

tff(fact_43_rel__simps_I4_J,axiom,
    ! [K3: int] :
      ( ord_less(int,pls,bit0(K3))
    <=> ord_less(int,pls,K3) ) ).

tff(fact_44_nat__numeral__1__eq__1,axiom,
    number_number_of(nat,bit1(pls)) = one_one(nat) ).

tff(fact_45_rel__simps_I22_J,axiom,
    ! [K3: int] :
      ( ord_less_eq(int,pls,bit1(K3))
    <=> ord_less_eq(int,pls,K3) ) ).

tff(fact_46_rel__simps_I32_J,axiom,
    ! [L: int,K3: int] :
      ( ord_less_eq(int,bit0(K3),bit1(L))
    <=> ord_less_eq(int,K3,L) ) ).

tff(fact_47_add__Bit1__Bit0,axiom,
    ! [L1: int,K: int] : plus_plus(int,bit1(K),bit0(L1)) = bit1(plus_plus(int,K,L1)) ).

tff(fact_48_add__Bit0__Bit1,axiom,
    ! [L1: int,K: int] : plus_plus(int,bit0(K),bit1(L1)) = bit1(plus_plus(int,K,L1)) ).

tff(fact_49_le__nat__number__of,axiom,
    ! [V3: int,V2: int] :
      ( ord_less_eq(nat,number_number_of(nat,V2),number_number_of(nat,V3))
    <=> ( ~ ord_less_eq(int,V2,V3)
       => ord_less_eq(int,V2,pls) ) ) ).

tff(fact_50_power__eq__0__iff__number__of,axiom,
    ! [A: $tType] :
      ( ( power(A)
        & mult_zero(A)
        & no_zero_divisors(A)
        & zero_neq_one(A) )
     => ! [W: int,A2: A] :
          ( ( power_power(A,A2,number_number_of(nat,W)) = zero_zero(A) )
        <=> ( ( A2 = zero_zero(A) )
            & ( number_number_of(nat,W) != zero_zero(nat) ) ) ) ) ).

tff(fact_51_rel__simps_I29_J,axiom,
    ! [K3: int] :
      ( ord_less_eq(int,bit1(K3),pls)
    <=> ord_less(int,K3,pls) ) ).

tff(fact_52_rel__simps_I5_J,axiom,
    ! [K3: int] :
      ( ord_less(int,pls,bit1(K3))
    <=> ord_less_eq(int,pls,K3) ) ).

tff(fact_53_eq__number__of__0,axiom,
    ! [V2: int] :
      ( ( number_number_of(nat,V2) = zero_zero(nat) )
    <=> ord_less_eq(int,V2,pls) ) ).

tff(fact_54_eq__0__number__of,axiom,
    ! [V2: int] :
      ( ( zero_zero(nat) = number_number_of(nat,V2) )
    <=> ord_less_eq(int,V2,pls) ) ).

tff(fact_55_rel__simps_I33_J,axiom,
    ! [L: int,K3: int] :
      ( ord_less_eq(int,bit1(K3),bit0(L))
    <=> ord_less(int,K3,L) ) ).

tff(fact_56_rel__simps_I15_J,axiom,
    ! [L: int,K3: int] :
      ( ord_less(int,bit0(K3),bit1(L))
    <=> ord_less_eq(int,K3,L) ) ).

tff(fact_57_zle__add1__eq__le,axiom,
    ! [Z1: int,W: int] :
      ( ord_less(int,W,plus_plus(int,Z1,one_one(int)))
    <=> ord_less_eq(int,W,Z1) ) ).

tff(fact_58_less__special_I3_J,axiom,
    ! [A: $tType] :
      ( ( number_ring(A)
        & linordered_idom(A) )
     => ! [X1: int] :
          ( ord_less(A,number_number_of(A,X1),zero_zero(A))
        <=> ord_less(int,X1,pls) ) ) ).

tff(fact_59_less__special_I1_J,axiom,
    ! [A: $tType] :
      ( ( number_ring(A)
        & linordered_idom(A) )
     => ! [Y: int] :
          ( ord_less(A,zero_zero(A),number_number_of(A,Y))
        <=> ord_less(int,pls,Y) ) ) ).

tff(fact_60_one__add__one__is__two,axiom,
    ! [A: $tType] :
      ( number_ring(A)
     => ( plus_plus(A,one_one(A),one_one(A)) = number_number_of(A,bit0(bit1(pls))) ) ) ).

tff(fact_61_less__special_I4_J,axiom,
    ! [A: $tType] :
      ( ( number_ring(A)
        & linordered_idom(A) )
     => ! [X1: int] :
          ( ord_less(A,number_number_of(A,X1),one_one(A))
        <=> ord_less(int,X1,bit1(pls)) ) ) ).

tff(fact_62_less__special_I2_J,axiom,
    ! [A: $tType] :
      ( ( number_ring(A)
        & linordered_idom(A) )
     => ! [Y: int] :
          ( ord_less(A,one_one(A),number_number_of(A,Y))
        <=> ord_less(int,bit1(pls),Y) ) ) ).

tff(fact_63_add__special_I3_J,axiom,
    ! [A: $tType] :
      ( number_ring(A)
     => ! [V: int] : plus_plus(A,number_number_of(A,V),one_one(A)) = number_number_of(A,plus_plus(int,V,bit1(pls))) ) ).

tff(fact_64_add__special_I2_J,axiom,
    ! [A: $tType] :
      ( number_ring(A)
     => ! [W1: int] : plus_plus(A,one_one(A),number_number_of(A,W1)) = number_number_of(A,plus_plus(int,bit1(pls),W1)) ) ).

tff(fact_65_zero__less__power2,axiom,
    ! [A: $tType] :
      ( linordered_idom(A)
     => ! [A2: A] :
          ( ord_less(A,zero_zero(A),power_power(A,A2,number_number_of(nat,bit0(bit1(pls)))))
        <=> ( A2 != zero_zero(A) ) ) ) ).

tff(fact_66_plus__numeral__code_I9_J,axiom,
    ! [W1: int,V: int] : plus_plus(int,number_number_of(int,V),number_number_of(int,W1)) = number_number_of(int,plus_plus(int,V,W1)) ).

tff(fact_67_less__number__of__int__code,axiom,
    ! [L: int,K3: int] :
      ( ord_less(int,number_number_of(int,K3),number_number_of(int,L))
    <=> ord_less(int,K3,L) ) ).

tff(fact_68_less__eq__number__of__int__code,axiom,
    ! [L: int,K3: int] :
      ( ord_less_eq(int,number_number_of(int,K3),number_number_of(int,L))
    <=> ord_less_eq(int,K3,L) ) ).

tff(fact_69_even__less__0__iff,axiom,
    ! [A: $tType] :
      ( linordered_idom(A)
     => ! [A2: A] :
          ( ord_less(A,plus_plus(A,A2,A2),zero_zero(A))
        <=> ord_less(A,A2,zero_zero(A)) ) ) ).

tff(fact_70_number__of__add,axiom,
    ! [A: $tType] :
      ( number_ring(A)
     => ! [W1: int,V: int] : number_number_of(A,plus_plus(int,V,W1)) = plus_plus(A,number_number_of(A,V),number_number_of(A,W1)) ) ).

tff(fact_71_zless__add1__eq,axiom,
    ! [Z1: int,W: int] :
      ( ord_less(int,W,plus_plus(int,Z1,one_one(int)))
    <=> ( ord_less(int,W,Z1)
        | ( W = Z1 ) ) ) ).

tff(fact_72_zero__is__num__zero,axiom,
    zero_zero(int) = number_number_of(int,pls) ).

tff(fact_73_semiring__norm_I113_J,axiom,
    zero_zero(nat) = number_number_of(nat,pls) ).

tff(fact_74_add__Pls__right,axiom,
    ! [K: int] : plus_plus(int,K,pls) = K ).

tff(fact_75_add__Pls,axiom,
    ! [K: int] : plus_plus(int,pls,K) = K ).

tff(fact_76_Bit0__def,axiom,
    ! [K: int] : bit0(K) = plus_plus(int,K,K) ).

tff(fact_77_less__int__code_I16_J,axiom,
    ! [K2: int,K1: int] :
      ( ord_less(int,bit1(K1),bit1(K2))
    <=> ord_less(int,K1,K2) ) ).

tff(fact_78_less__int__code_I13_J,axiom,
    ! [K2: int,K1: int] :
      ( ord_less(int,bit0(K1),bit0(K2))
    <=> ord_less(int,K1,K2) ) ).

tff(fact_79_less__int__def,axiom,
    ! [W: int,Z1: int] :
      ( ord_less(int,Z1,W)
    <=> ( ord_less_eq(int,Z1,W)
        & ( Z1 != W ) ) ) ).

tff(fact_80_one__is__num__one,axiom,
    one_one(int) = number_number_of(int,bit1(pls)) ).

tff(fact_81_Numeral1__eq1__nat,axiom,
    one_one(nat) = number_number_of(nat,bit1(pls)) ).

tff(fact_82_odd__less__0__iff,axiom,
    ! [Z1: int] :
      ( ord_less(int,plus_plus(int,plus_plus(int,one_one(int),Z1),Z1),zero_zero(int))
    <=> ord_less(int,Z1,zero_zero(int)) ) ).

tff(fact_83_zless__imp__add1__zle,axiom,
    ! [Z: int,W1: int] :
      ( ord_less(int,W1,Z)
     => ord_less_eq(int,plus_plus(int,W1,one_one(int)),Z) ) ).

tff(fact_84_add1__zle__eq,axiom,
    ! [Z1: int,W: int] :
      ( ord_less_eq(int,plus_plus(int,W,one_one(int)),Z1)
    <=> ord_less(int,W,Z1) ) ).

tff(fact_85_number__of__reorient,axiom,
    ! [A: $tType] :
      ( number(A)
     => ! [X1: A,W: int] :
          ( ( number_number_of(A,W) = X1 )
        <=> ( X1 = number_number_of(A,W) ) ) ) ).

tff(fact_86_le__number__of__eq__not__less,axiom,
    ! [A: $tType] :
      ( ( number(A)
        & linorder(A) )
     => ! [W: int,V2: int] :
          ( ord_less_eq(A,number_number_of(A,V2),number_number_of(A,W))
        <=> ~ ord_less(A,number_number_of(A,W),number_number_of(A,V2)) ) ) ).

tff(fact_87_add__numeral__0,axiom,
    ! [A: $tType] :
      ( number_ring(A)
     => ! [A1: A] : plus_plus(A,number_number_of(A,pls),A1) = A1 ) ).

tff(fact_88_add__numeral__0__right,axiom,
    ! [A: $tType] :
      ( number_ring(A)
     => ! [A1: A] : plus_plus(A,A1,number_number_of(A,pls)) = A1 ) ).

tff(fact_89_less__int__code_I15_J,axiom,
    ! [K2: int,K1: int] :
      ( ord_less(int,bit1(K1),bit0(K2))
    <=> ord_less(int,K1,K2) ) ).

tff(fact_90_bin__less__0__simps_I4_J,axiom,
    ! [W: int] :
      ( ord_less(int,bit1(W),zero_zero(int))
    <=> ord_less(int,W,zero_zero(int)) ) ).

tff(fact_91_bin__less__0__simps_I1_J,axiom,
    ~ ord_less(int,pls,zero_zero(int)) ).

tff(fact_92_bin__less__0__simps_I3_J,axiom,
    ! [W: int] :
      ( ord_less(int,bit0(W),zero_zero(int))
    <=> ord_less(int,W,zero_zero(int)) ) ).

tff(fact_93_Bit1__def,axiom,
    ! [K: int] : bit1(K) = plus_plus(int,plus_plus(int,one_one(int),K),K) ).

tff(fact_94_odd__nonzero,axiom,
    ! [Z: int] : plus_plus(int,plus_plus(int,one_one(int),Z),Z) != zero_zero(int) ).

tff(fact_95_semiring__add__number__of,axiom,
    ! [A: $tType] :
      ( number_semiring(A)
     => ! [V1: int,V: int] :
          ( ord_less_eq(int,pls,V)
         => ( ord_less_eq(int,pls,V1)
           => ( plus_plus(A,number_number_of(A,V),number_number_of(A,V1)) = number_number_of(A,plus_plus(int,V,V1)) ) ) ) ) ).

tff(fact_96_le__imp__0__less,axiom,
    ! [Z: int] :
      ( ord_less_eq(int,zero_zero(int),Z)
     => ord_less(int,zero_zero(int),plus_plus(int,one_one(int),Z)) ) ).

tff(fact_97_int__pos__lt__two__imp__zero__or__one,axiom,
    ! [X: int] :
      ( ord_less_eq(int,zero_zero(int),X)
     => ( ord_less(int,X,number_number_of(int,bit0(bit1(pls))))
       => ( ( X = zero_zero(int) )
          | ( X = one_one(int) ) ) ) ) ).

%----Arities (24)
tff(arity_Int_Oint___Groups_Olinordered__ab__group__add,axiom,
    linord219039673up_add(int) ).

tff(arity_Int_Oint___Rings_Oring__1__no__zero__divisors,axiom,
    ring_11004092258visors(int) ).

tff(arity_Int_Oint___Rings_Ono__zero__divisors,axiom,
    no_zero_divisors(int) ).

tff(arity_Int_Oint___Rings_Olinordered__idom,axiom,
    linordered_idom(int) ).

tff(arity_Int_Oint___Int_Onumber__semiring,axiom,
    number_semiring(int) ).

tff(arity_Int_Oint___Rings_Ozero__neq__one,axiom,
    zero_neq_one(int) ).

tff(arity_Int_Oint___Orderings_Olinorder,axiom,
    linorder(int) ).

tff(arity_Int_Oint___Rings_Osemiring__1,axiom,
    semiring_1(int) ).

tff(arity_Int_Oint___Rings_Osemiring__0,axiom,
    semiring_0(int) ).

tff(arity_Int_Oint___Rings_Omult__zero,axiom,
    mult_zero(int) ).

tff(arity_Int_Oint___Int_Oring__char__0,axiom,
    ring_char_0(int) ).

tff(arity_Int_Oint___Int_Onumber__ring,axiom,
    number_ring(int) ).

tff(arity_Int_Oint___Power_Opower,axiom,
    power(int) ).

tff(arity_Int_Oint___Int_Onumber,axiom,
    number(int) ).

tff(arity_Nat_Onat___Rings_Ono__zero__divisors,axiom,
    no_zero_divisors(nat) ).

tff(arity_Nat_Onat___Int_Onumber__semiring,axiom,
    number_semiring(nat) ).

tff(arity_Nat_Onat___Rings_Ozero__neq__one,axiom,
    zero_neq_one(nat) ).

tff(arity_Nat_Onat___Orderings_Olinorder,axiom,
    linorder(nat) ).

tff(arity_Nat_Onat___Rings_Osemiring__1,axiom,
    semiring_1(nat) ).

tff(arity_Nat_Onat___Rings_Osemiring__0,axiom,
    semiring_0(nat) ).

tff(arity_Nat_Onat___Rings_Omult__zero,axiom,
    mult_zero(nat) ).

tff(arity_Nat_Onat___Power_Opower,axiom,
    power(nat) ).

tff(arity_Nat_Onat___Int_Onumber,axiom,
    number(nat) ).

tff(arity_HOL_Obool___Orderings_Olinorder,axiom,
    linorder(bool) ).

%----Helper facts (2)
tff(help_pp_1_1_U,axiom,
    ~ pp(fFalse) ).

tff(help_pp_2_1_U,axiom,
    pp(fTrue) ).

%----Conjectures (1)
tff(conj_0,conjecture,
    $false ).

%------------------------------------------------------------------------------
